"""add tasks dictation_items submissions mistakes tables

Revision ID: b8f589663c94
Revises: ab857114e5d3
Create Date: 2026-05-10 17:31:56.797021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db_types import GUID


# revision identifiers, used by Alembic.
revision: str = 'b8f589663c94'
down_revision: Union[str, None] = 'ab857114e5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('family_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_date'), 'tasks', ['date'], unique=False)
    op.create_index(op.f('ix_tasks_family_id'), 'tasks', ['family_id'], unique=False)
    op.create_table('dictation_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pause_interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictation_items_task_id'), 'dictation_items', ['task_id'], unique=False)
    op.create_table('mistakes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistakes_task_id'), 'mistakes', ['task_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_mistakes_task_id'), table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_index(op.f('ix_dictation_items_task_id'), table_name='dictation_items')
    op.drop_table('dictation_items')
    op.drop_index(op.f('ix_tasks_family_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_date'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
