"""add admins table and soft delete fields

Revision ID: c7919be721dd
Revises: b8f589663c94
Create Date: 2026-06-16 14:49:00.211552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7919be721dd'
down_revision: Union[str, None] = 'b8f589663c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.drop_constraint('dictation_items_ibfk_1', 'dictation_items', type_='foreignkey')
    op.create_foreign_key(None, 'dictation_items', 'tasks', ['task_id'], ['id'])
    op.add_column('families', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('mistakes_ibfk_1', 'mistakes', type_='foreignkey')
    op.create_foreign_key(None, 'mistakes', 'tasks', ['task_id'], ['id'])
    op.drop_constraint('submissions_ibfk_1', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'families', ['family_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'families', ['family_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_1', 'tasks', 'families', ['family_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('tasks', 'is_deleted')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_ibfk_1', 'submissions', 'tasks', ['task_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'mistakes', type_='foreignkey')
    op.create_foreign_key('mistakes_ibfk_1', 'mistakes', 'tasks', ['task_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('families', 'is_deleted')
    op.drop_constraint(None, 'dictation_items', type_='foreignkey')
    op.create_foreign_key('dictation_items_ibfk_1', 'dictation_items', 'tasks', ['task_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
